---
name: Build

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "42 7 15 * *"

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Test building image.
        run: docker build -t container .

      - name: Run the built image.
        run: >
          docker run -e USER='admin' -e PASSWORD='password'
          -e LISTEN_METHOD='irc+insecure' -e LISTEN_HOST='0.0.0.0'
          -e LISTEN_PORT='6667' -e LOG_PATH=/data/irc.log
          --name test-container -d container

      - name: Verify that the container works
        run: docker exec --tty test-container env TERM=xterm cat /etc/os-release

  # If on main branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ github.repository }}:latest